version: '0.3'

services:
  webapi:
    image: 'webapi-image:latest'
    build: 
      context: ./MusicServerAPI
      dockerfile: Dockerfile
    ports: 
      - "5070:80"
      - "443:443"
    environment:
      - ConnectionStrings__MusicServerAPI=User ID=postgres;Server=host.docker.internal;Port=5432;Database=music_pg;Password=postgres;Pooling=True;
      - ASPNETCORE_URLS=http://+80
    networks:
      - backend
      - frontend
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=music_pg
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app-data:/var/lib/postgresql/data
    networks:
      - backend
    

  webclient:
    image: 'webclient-image:latest'
    build:
      context: ./MusicClient/client-app
    ports:
      - "3000:3000"
    depends_on:
      - webapi
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  app-data:
