# Generated by Django 4.2.5 on 2023-10-01 11:05

from django.db import migrations
import users.custom_field


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=users.custom_field.HashedPrimaryKeyField(default=users.custom_field.HashedPrimaryKeyField.generate_hash, editable=False, max_length=32, unique=True),
        ),
    ]
